print("helloworld")
print("Hello again")
print("I like typing this.")
print("This is fun.")
print('Yay! Printing.')
print("I'd much rather you 'not'.")
print('i "said" do not  touch this.')
print("\"what\" are you talking about?")